Repository ariebrainware/paylist, pull requests merged in 2019-10, with the labels that each got.

#7 Feature/implement logout
  assets/images/logout.png
  bash.exe.stackdump
  navigation/MainTabNavigator.js
  screens/CreatePaylist.js
  screens/HomeScreen.js
  screens/LoginScreen.js
  screens/RegisterScreen.js
  screens/SettingsScreen.js
  service/deviceStorage.js
Labels: enhancement

#14 Feature/revamp assets
  App.js
  app.json
  assets/images/add-button.png
  assets/images/icon.png
  assets/images/robot-dev.png
  assets/images/robot-prod.png
  config.js
  navigation/MainTabNavigator.js
  package-lock.json
  package.json
  screens/CreatePaylist.js
  screens/HomeScreen.js
  test.js
Labels: enhancement

#15 First Major Release v1.0.0
  .eslintrc.json
  App.js
  __tests__/App-test.js
  app.json
  assets/images/add-button.png
  assets/images/ceklis.png
  assets/images/icon.png
  assets/images/logout.png
  assets/images/robot-dev.png
  assets/images/robot-prod.png
  babel.config.js
  bash.exe.stackdump
  components/StyledText.js
  components/TabBarIcon.js
  components/__tests__/StyledText-test.js
  config.js
  constants/Colors.js
  constants/Layout.js
  navigation/AppNavigator.js
  navigation/AppNavigator.web.js
  navigation/MainTabNavigator.js
  package-lock.json
  package.json
  screens/CreatePaylist.js
  screens/HomeScreen.js
  screens/LinksScreen.js
  screens/LoginScreen.js
  screens/RegisterScreen.js
  screens/SettingsScreen.js
  screens/UpdatePaylist.js
  screens/UpdateUser.js
  service/deviceStorage.js
  yarn.lock
Labels: enhancement

#16 Remove unused console log
  screens/CreatePaylist.js
  screens/HomeScreen.js
  screens/LoginScreen.js
  screens/RegisterScreen.js
  screens/SettingsScreen.js
  screens/UpdatePaylist.js
  screens/UpdateUser.js
  service/deviceStorage.js
Labels: bug

#18 Hotfix: Remove console log
  screens/UpdatePaylist.js
  service/deviceStorage.js
Labels: bug, enhancement

#19 Feature/revamp assets
  State.js
  assets/images/splash.png
  config.js
  constants/Colors.js
  navigation/MainTabNavigator.js
  package-lock.json
  package.json
  screens/CreatePaylist.js
  screens/HomeScreen.js
  screens/LinksScreen.js
  screens/LoginScreen.js
  screens/RegisterScreen.js
  screens/SettingsScreen.js
  screens/UpdatePaylist.js
  screens/UpdateUser.js
  service/deviceStorage.js
Labels: enhancement

#23 implement checklist, floating button and searchbar
  navigation/AppNavigator.js
  package-lock.json
  package.json
  screens/AddBalance.js
  screens/CreatePaylist.js
  screens/HomeScreen.js
  screens/LoginScreen.js
  screens/RegisterScreen.js
  screens/SettingsScreen.js
  screens/UpdateUser.js
Labels: enhancement

#27 Feature/revamp assets
  .eslintrc.json
  State.js
  config.js
  navigation/AppNavigator.js
  navigation/MainTabNavigator.js
  screens/AddBalance.js
  screens/CreatePaylist.js
  screens/Drawer.js
  screens/EditPassword.js
  screens/HomeScreen.js
  screens/LinksScreen.js
  screens/LoginScreen.js
  screens/RegisterScreen.js
  screens/SettingsScreen.js
  screens/UpdatePaylist.js
  screens/UpdateUser.js
Labels: enhancement

#28 fix back button hardware
  navigation/MainTabNavigator.js
  screens/AddBalance.js
  screens/CreatePaylist.js
  screens/EditPassword.js
  screens/HomeScreen.js
  screens/SettingsScreen.js
  screens/UpdatePaylist.js
  screens/UpdateUser.js
Labels: enhancement

#29 Minor Release v1.1.1
  .eslintrc.json
  State.js
  config.js
  navigation/AppNavigator.js
  navigation/MainTabNavigator.js
  screens/AddBalance.js
  screens/CreatePaylist.js
  screens/Drawer.js
  screens/EditPassword.js
  screens/HomeScreen.js
  screens/LinksScreen.js
  screens/LoginScreen.js
  screens/RegisterScreen.js
  screens/SettingsScreen.js
  screens/UpdatePaylist.js
  screens/UpdateUser.js
Labels: bug, enhancement, priority:high
